### PR TITLE
feat: cursor to pointer for slider and color-picker

### LINKED ISSUE #6: Set the cursor to pointer while hovering over sliders
Maybe it would be better visually if the cursor turns into a pointer while hovering over the padding-sliders

### PR DESCRIPTION
**Pull request by alefDev-prog**
fixes #6

Affected files: 

- _src/components/ui/Input.tsx_
- _src/components/ui/Slider.tsx_

What I have done:

- Just added a style attribute with cursor set to pointer

### CODE REVIEW

**Review by ekqt — COMMENTED** [review]
Thanks for this PR! It's looking good but could you try to use a utility class for this instead of inline styles to keep the UI components consistent?

https://tailwindcss.com/docs/cursor

**Comment by alefDev-prog** [comment]
Of, course! I have changed that now

**Review by ekqt — APPROVED** [review]
Looking good!

**Comment by ekqt** [comment]
Thanks for the PR. Will add you to the contributors section shortly. Still have to add that part in the readme file.

**Comment by ekqt** [comment]
@all-contributors please add @alefDev-prog for code

**Pull request merged**
