### PR TITLE
feat: add toasts

### LINKED ISSUE #10: Integrate Toasts
Integrate Toasts on the application to provide user feedback. This would be specially great for when the clipboard's image is captured.

Grab inspo from: https://ui.shadcn.com/docs/components/toast

Context: When the user tries to use an asset that isn't an image from their clipboard, an error is printed to the console from:
https://github.com/ekqt/screenshot/blob/main/src/utils/clipboard.ts

Improve the experience by triggering a success toast instead when the image has been received successfully and a failure toast when no image type has been found

### PR DESCRIPTION
**Pull request by alefDev-prog**
fixes #10

Affected files: 

- _src/app/page.tsx_
- _src/utils/clipboard.ts_

What I have done:

1. Installed npm package _react-toastify_
2. Inserted the `ToastContainer` in _page.tsx_
3.  Call toast-functions in _clipboard.ts_ on fail and success

Issue I have encountered:

I have encountered an issue in _src/components/ClipboardImage.tsx_. The component in this file re-renders multiple times when clicking on the picture in the frame. This causes the `pasteImage` function to be called multiple times, resulting in several toasts apperaing on a single click. I think that the issue is with the `imageCallback` function and how it uses the `useCallback` hook. The items in its dependency-array are being changed within the function itself, something I think causes this issue. 

I have tried to solve this issue without changing the `useCallback` hook but without success. As I wrote before, this results in multiple toasts appearing on a single click.

### CODE REVIEW

**Review by ekqt — CHANGES_REQUESTED** [review]
Hey, @alefDev-prog . This issue could be definitely cause by this. 

However, before anything. I'd like to focus on implementing the toasts following: https://ui.shadcn.com/docs/components/toast

We can use the manual installation and copy the entire implementation, just make sure to adapt and use TailwindCSS colors.

This is the main AC from this issue. Once we've implemented the toasts to fit the UI we can then figure out what refactoring do we need in the component itself.

Since it is a bit of refactoring needed, I can take over this one if you'd need. I'm not happy with `react-toastify` package because we're using Radix for the most part and it falls outside of the UI aesthetic.

**Comment by alefDev-prog** [comment]
Hi, ok sure I use your prefered package instead.

**Comment by ekqt** [comment]
We're heavily inspiring our look from that library so that's why I'm pushing for consistency. Sorry, I appreciate your help. It's just going to make it easier for all of us. @alefDev-prog

**Comment by ekqt** [comment]
@alefDev-prog good work here! Unfortunately, I cannot collaborate in this PR because you didn't use a branch and are working off main. In the future to ensure collaboration please from your forked repository open a branch.

> _When contributors fork your repository and intend to make changes or additions, it is generally recommended for them to create a separate branch in their forked repository. They should make their changes on that branch and then open a pull request (PR) from their branch to the main branch of your repository_

**Review by ekqt — APPROVED** [review]

**Pull request merged**
